name: FST_dxy
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - alsa-lib=1.2.15.3=hb03c661_0
  - anyio=4.12.1=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4c3975b_2
  - arrow=1.4.0=pyhcf101f3_0
  - asciitree=0.3.3=py_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.2=h206d751_0
  - azure-identity-cpp=1.13.3=hed0cdb0_1
  - azure-storage-blobs-cpp=12.16.0=hdd73cc9_1
  - azure-storage-common-cpp=12.12.0=ha7a2c86_1
  - azure-storage-files-datalake-cpp=12.14.0=h52c5a47_1
  - babel=2.18.0=pyhcf101f3_0
  - backports.zstd=1.3.0=py312h90b7ffd_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bed-reader=1.0.0=py312hc521ac2_0
  - bio2zarr=0.1.6=pyhdfd78af_0
  - bleach=6.3.0=pyhcf101f3_1
  - bleach-with-css=6.3.0=hbca2aae_1
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli-python=1.2.0=py312hdb49522_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he90730b_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h0a2e395_4
  - cpython=3.12.12=py312hd8ed1ab_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - cytoolz=1.1.0=py312h4c3975b_1
  - cyvcf2=0.31.0=py312h16c6d63_1
  - dask=2024.8.0=pyhd8ed1ab_0
  - dask-core=2024.8.0=pyhd8ed1ab_0
  - dask-expr=1.1.10=pyhd8ed1ab_0
  - dask-glm=0.3.2=pyhd8ed1ab_0
  - dask-ml=2024.4.4=pyhd8ed1ab_1
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.20=py312h8285ef7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_1
  - distributed=2024.8.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fasteners=0.19=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glib=2.86.3=h5192d8d_0
  - glib-tools=2.86.3=hf516916_0
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.26.10=h0363672_0
  - gstreamer=1.26.10=h17cb667_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h6083320_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.23=h566b1c6_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.2.0=pyha191276_1
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter=1.1.1=py312h06a4308_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - libabseil=20260107.1=cxx17_h7b12aa8_0
  - libarrow=23.0.0=h2603568_3_cpu
  - libarrow-acero=23.0.0=h635bf11_3_cpu
  - libarrow-compute=23.0.0=h53684a4_3_cpu
  - libarrow-dataset=23.0.0=h635bf11_3_cpu
  - libarrow-substrait=23.0.0=hb4dd7c2_3_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_17
  - libgoogle-cloud=2.39.0=h9d11ab5_1
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_1
  - libgrpc=1.78.0=h1d1128b_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=h9692893_2
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_2
  - libopus=1.6.1=h280c20c_0
  - libparquet=23.0.0=h7376487_3_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.55=h421ea60_0
  - libpq=18.1=hb80d175_3
  - libprotobuf=6.33.5=h2b00c02_0
  - libre2-11=2025.11.05=h0dc7533_1
  - libsndfile=1.2.2=hc7d488a_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libsystemd0=259.1=h6569c3e_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.0=hc4654cb_2
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.46.0=py312h7424e68_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py312h3d67a73_1
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py312h8a5da7c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.2=py312hd9148b4_1
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.16.0=pyhcf101f3_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert=7.17.0=h14065e2_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbconvert-pandoc=7.17.0=hc3985f0_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h54a6638_1
  - notebook=7.5.3=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numba=0.63.1=py312hd1dde6f_0
  - numcodecs=0.15.1=py312hf79963d_1
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - orc=2.2.2=hbb90d81_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py312h8ecdadd_0
  - pandoc=3.9=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=hadf4263_0
  - parso=0.8.6=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.47=haa7fec5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=11.3.0=py312h7b42cdd_3
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.9.0=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.2.2=py312h5253ce2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=h9a6aba3_3
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=23.0.0=py312h7900ff3_0
  - pyarrow-core=23.0.0=py312h2054cf2_0_cpu
  - pyarrow-hotfix=0.7=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyqt=5.15.11=py312h82c0db2_2
  - pyqt5-sip=12.17.0=py312h1289d80_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd63d673_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_2
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_1
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qt-main=5.15.15=hc240232_7
  - qtconsole=5.7.1=pyhd8ed1ab_0
  - qtconsole-base=5.7.1=pyha770c72_0
  - qtpy=2.4.3=pyhd8ed1ab_1
  - re2=2025.11.05=h5301d42_1
  - readline=8.3=h853b02a_0
  - rechunker=0.5.4=pyhd8ed1ab_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py312h868fb18_0
  - s2n=1.6.2=he8a4886_1
  - samtools=1.23=h96c455f_0
  - scikit-learn=1.8.0=np2py312h3226591_1
  - scipy=1.17.0=py312h54fa4ab_1
  - send2trash=2.1.0=pyha191276_0
  - setuptools=82.0.0=pyh332efcf_0
  - sgkit=0.10.0=pyhd8ed1ab_0
  - sip=6.10.0=py312h1289d80_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sparse=0.17.0=pyhcf101f3_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhcf101f3_3
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h366c992_103
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py312h961da02_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - tskit=1.0.1=py312h4f23490_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wrapt=2.1.1=py312h4c3975b_0
  - xarray=2025.3.0=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zarr=2.18.7=pyhd8ed1ab_0
  - zeromq=4.3.5=h387f397_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/inf-33-2025/miniconda3/envs/FST_dxy
